cmake: suppress unused-function warning for llama.cpp (#2452)
## Issue

We got the following error when we built Groonga with MariaDB.

```
/home/buildbot/_deps/llama_cpp-src/ggml/src/ggml-impl.h:111:13: error: 'void ggml_set_op_params(ggml_tensor*, const void*, size_t)' defined but not used [-Werror=unused-function]
  111 | static void ggml_set_op_params(struct ggml_tensor * tensor, const void * params, size_t params_size) {
      |             ^~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
```

## Cause

When building Groonga with MariaDB, the bundled
llama.cpp triggers `-Werror=unused-function`.

## Solution

Since upstream llama.cpp defines these static helpers even if we don’t
call them now, add
`-Wno-unused-function` to Debug and RelWithDebInfo builds to suppress
the error.