windows: remove needless cast
It causes build error on C++:

    C:\projects\groonga\lib\dat.cpp(133): error C2665: '_InterlockedExchangeAdd' : none of the 4 overloads could convert all the argument types [C:\projects\groonga\lib\libgroonga.vcxproj]
              C:\Program Files (x86)\Windows Kits\8.1\Include\um\winbase.h(8964): could be 'unsigned __int64 _InterlockedExchangeAdd(volatile unsigned __int64 *,unsigned __int64)'
              C:\Program Files (x86)\Windows Kits\8.1\Include\um\winbase.h(8942): or       'unsigned long _InterlockedExchangeAdd(volatile unsigned long *,unsigned long)'
              C:\Program Files (x86)\Windows Kits\8.1\Include\um\winbase.h(8922): or       'unsigned int _InterlockedExchangeAdd(volatile unsigned int *,unsigned int)'
              C:\Program Files (x86)\Windows Kits\8.1\Include\um\winnt.h(5227): or       'LONG _InterlockedExchangeAdd(volatile LONG *,LONG)'
              while trying to match the argument list '(int32_t *, int32_t)'
    C:\projects\groonga\lib\dat.cpp(1167): error C2665: '_InterlockedExchangeAdd' : none of the 4 overloads could convert all the argument types [C:\projects\groonga\lib\libgroonga.vcxproj]
              C:\Program Files (x86)\Windows Kits\8.1\Include\um\winbase.h(8964): could be 'unsigned __int64 _InterlockedExchangeAdd(volatile unsigned __int64 *,unsigned __int64)'
              C:\Program Files (x86)\Windows Kits\8.1\Include\um\winbase.h(8942): or       'unsigned long _InterlockedExchangeAdd(volatile unsigned long *,unsigned long)'
              C:\Program Files (x86)\Windows Kits\8.1\Include\um\winbase.h(8922): or       'unsigned int _InterlockedExchangeAdd(volatile unsigned int *,unsigned int)'
              C:\Program Files (x86)\Windows Kits\8.1\Include\um\winnt.h(5227): or       'LONG _InterlockedExchangeAdd(volatile LONG *,LONG)'
              while trying to match the argument list '(int32_t *, int32_t)'