ci msys2: Add mruby patch for Windows ARM64 support (#2648)
GitHub: GH-2646

We add a patch to fix the following build error about mruby on Windows
ARM64 environments. The patch modifies mruby's `throw.h` to avoid using
`__builtin_setjmp` and `__builtin_longjmp` on ARM64, which are not
supported.

```
C:/a/groonga/groonga/ci/msys2/src/groonga-15.2.1/vendor/mruby-source/src/error.c:631:5: error: __builtin_setjmp is not supported for the current target
  631 |     MRB_TRY(&c_jmp) {
      |     ^~~~~~~~~~~~~~~
C:/a/groonga/groonga/ci/msys2/src/groonga-15.2.1/vendor/mruby-source/include/mruby/throw.h:44:26: note: expanded from macro 'MRB_TRY'
   44 | #define MRB_TRY(buf) if (MRB_SETJMP((buf)->impl) == 0) {
      |                          ^~~~~~~~~~~~~~~~~~~~~~~
C:/a/groonga/groonga/ci/msys2/src/groonga-15.2.1/vendor/mruby-source/include/mruby/throw.h:37:20: note: expanded from macro 'MRB_SETJMP'
   37 | #define MRB_SETJMP __builtin_setjmp
      |                    ^
4 warnings and 4 errors generated.
rake aborted!
```
ref:
https://github.com/groonga/groonga/actions/runs/19283288685/job/55138731280#step:8:936

This is a temporary workaround as the issue has already been resolved
upstream: https://github.com/mruby/mruby/issues/6637.
The patch can be removed once bundled mruby is updated to a version that
includes the upstream fix.