use standard uint32_t instead of non-standard __uint32_t
this fixes the following build error with musl libc:
    lib/com.c: In function 'grn_com_event_add':
    lib/com.c:351:17: error: '__uint32_t' undeclared
    (first use in this function)
         e.events = (__uint32_t) events;
                     ^

fixes #375