rake: fix x post task
The client does not have a `refresh_token!`.
The following error occurs:

```
rake aborted!
NoMethodError: undefined method 'refresh_token!' for an instance of X::Client (NoMethodError)

      x_client.refresh_token!
              ^^^^^^^^^^^^^^^
Did you mean?  refresh_token
```

Since `OAuth2Authenticator` has the `refresh_token!`, it will call it.
https://rubydoc.info/gems/x/X/OAuth2Authenticator#refresh_token!-instance_method