remove `vptr` sanitize because it's not included in future features
If `vptr` is enabled, the following errors are raised
during build steps because the vptr sanitizer requires
RTTI, but RTTI is disabled (by default).

```
[397/398] Linking C executable src/suggest/groonga-suggest-create-dataset
FAILED: src/suggest/groonga-suggest-create-dataset
: && /usr/bin/clang -fsanitize=undefined -fno-sanitize=alignment -g  src/suggest/CMakeFiles/groonga-suggest-create-dataset.dir/groonga_suggest_create_dataset.c.o -o src/suggest/groonga-suggest-create-dataset  -Wl,-rpath,/groonga.ubsan/lib:/groonga.ubsan/_deps/llama_cpp-build/src:/groonga.ubsan/_deps/llama_cpp-build/ggml/src:  lib/libgroonga.so.0.0.0  /usr/lib/x86_64-linux-gnu/libmsgpackc.so.2.0.0  _deps/llama_cpp-build/src/libgroonga-llama.so.0.0.0  _deps/llama_cpp-build/ggml/src/libgroonga-ggml.so.0.0.0  _deps/llama_cpp-build/ggml/src/libgroonga-ggml-base.so.0.0.0 && :
/usr/bin/ld: lib/libgroonga.so.0.0.0: undefined reference to `__ubsan_vptr_type_cache'
/usr/bin/ld: lib/libgroonga.so.0.0.0: undefined reference to `__ubsan_handle_dynamic_type_cache_miss'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

https://github.com/llvm/llvm-project/pull/121115