cmake: enable -Wsuggest-override warning and fix comparison
## Issue

We got the following error when we built Groonga with MariaDB.

```
2040-/home/buildbot/extra/groonga/lib/dat/dat.hpp:211:21: error: 'grn::dat::ErrorCode grn::dat::Error<T>::code() const [with grn::dat::ErrorCode T = grn::dat::SIZE_ERROR]' can be marked override [-Werror=suggest-override]
2041-  211 |   virtual ErrorCode code() const throw() {
2042-      |                     ^~~~
```

### Hot to reproduce

```
rm -rf ../groonga.build
cmake \
  -S . \
  -B ../groonga.build \
  --preset=debug-maximum \
  -DCMAKE_INSTALL_PREFIX=/tmp/local \
  -DCMAKE_CXX_FLAGS="-Werror=suggest-override" && \
cmake --build ../groonga.build
...
/home/otegami/work/c/groonga/lib/dat/dat.hpp:190:23: error: ‘virtual const char* grn::dat::Exception::what() const’ can be marked override [-Werror=suggest-override]
  190 |   virtual const char *what() const throw() {
      |                       ^~~~
...
```

## Causes

In MariaDB's build environment, compiler warnings are promoted to
errors.
As a result, any `-Wsuggest-override` diagnostics fail the build.

## Solution

This PR adds the `override` keyword to all virtual methods that override base
class methods.