json: add virtual destructor to TagWriter
MariaDB uses `-Wnon-virtual-dtor` and `-Werror` for debug build:

```text
/home/buildbot/extra/groonga/lib/json.cpp:112:10: error: 'struct {anonymous}::TagWriter' has virtual functions and accessible non-virtual destructor [-Werror=non-virtual-dtor]
/home/buildbot/extra/groonga/lib/json.cpp:130:10: error: base class 'struct {anonymous}::TagWriter' has accessible non-virtual destructor [-Werror=non-virtual-dtor]
/home/buildbot/extra/groonga/lib/json.cpp:130:10: error: 'struct {anonymous}::ContainerTagsWriter' has virtual functions and accessible non-virtual destructor [-Werror=non-virtual-dtor]
/home/buildbot/extra/groonga/lib/json.cpp:161:10: error: base class 'struct {anonymous}::TagWriter' has accessible non-virtual destructor [-Werror=non-virtual-dtor]
/home/buildbot/extra/groonga/lib/json.cpp:161:10: error: 'struct {anonymous}::RootTagWriter' has virtual functions and accessible non-virtual destructor [-Werror=non-virtual-dtor]
```

`TagWriter` has virtual functions. So it should have virtual
destructor.

We also enable `-Wnon-virtual-dtor` for Groonga to detect this
problem in our CI.

Co-Authored-By: Claude Opus 5.5 <noreply@anthropic.com>