Don't sign to already signed rpm when key is missing
It causes following the error for example.

  % rpm --checksig repositories/centos/5/source/SRPMS/MySQL-5.5.21-1.rhel5.src.rpm
  error: repositories/centos/5/source/SRPMS/MySQL-5.5.21-1.rhel5.src.rpm: sigh tags: BAD, no. of tags(33) out of range