cmake: Update simdjson version (#2430)
We got the following error when we built Groonga with MariaDB.

```
/home/buildbot/_deps/simdjson-src/include/simdjson/error.h:89:15: error: 'virtual const char* simdjson::simdjson_error::what() const' can be marked override [-Werror=suggest-override]
   89 |   const char *what() const noexcept { return error_message(error()); }
      |               ^~~~
```

This issue has already been resolved in simdjson v3.11.1. So we will
update the simdjson version.
ref: https://github.com/simdjson/simdjson/pull/2305