store: temporarily disable unused function (#3001)
Temporarily disable "grn_ja_is_full()" to suppress the unused-function
error in CI as below.

```
 /home/runner/work/groonga/groonga/lib/store.c:2393:1: error: unused function 'grn_ja_is_full' [-Werror,-Wunused-function]
 2393 | grn_ja_is_full(grn_ja *ja)
      | ^~~~~~~~~~~~~~
1 error generated.
```

This function will be used for column partitioning. So, this function
will be enabled when the required implementation is complete.