cmake: suppress no-unused-function warning for llama.cpp (#2483)
## Issue

We got the following error when we built Groonga with MariaDB.

```
/home/buildbot/_deps/llama_cpp-src/ggml/src/ggml-impl.h:111:13: error: 'void ggml_set_op_params(ggml_tensor*, const void*, size_t)' defined but not used [-Werror=unused-function]
  111 | static void ggml_set_op_params(struct ggml_tensor * tensor, const void * params, size_t params_size) {
      |             ^~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
```

## Cause

When building Groonga with MariaDB, the bundled llama.cpp triggers
`-Werror`.

## Solution

Upstream llama.cpp doesn't setup unused-function, so we suppress the
warning by explicitly passing `-Wno-unused-function` in Debug and
RelWithDebInfo builds.