cmake: suppress non-virtual-dtor warning for llama.cpp
## Issue

We got the following error when we built Groonga with MariaDB.

```
/home/buildbot/_deps/llama_cpp-src/src/llama-memory.h:7:7: error: 'class llama_memory_i' has virtual functions and accessible non-virtual destructor [-Werror=non-virtual-dtor]
    7 | class llama_memory_i {
      |       ^~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
```

## Cause

When building Groonga with MariaDB, the bundled llama.cpp triggers `-Werror`.

## Solution

Upstream llama.cpp doesn't setup non-virtual-dtor, so
we suppress the warning by explicitly passing `-Wno-non-virtual-dtor` in Debug and RelWithDebInfo builds.