autotools: enable C++20 for builds where supported
Update compiler flags to -std=c++20 from -std=c++17.
Because since version 24.0.0, Apache Arrow requires "std::span", which was introduced in C++20.
Ref: apache/arrow@df9dbbc

This change resolves the following error in Autotools workflow:

```
/usr/include/arrow/buffer.h:239:8: error: 'span' in namespace 'std' does not name a template type
  239 |   std::span<const T> span_as() const {
      |        ^~~~
/usr/include/arrow/buffer.h:239:3: note: 'std::span' is only available from C++20 onwards
  239 |   std::span<const T> span_as() const {
      |   ^~~
/usr/include/arrow/buffer.h:272:8: error: 'span' in namespace 'std' does not name a template type
  272 |   std::span<T> mutable_span_as() {
      |        ^~~~
/usr/include/arrow/buffer.h:272:3: note: 'std::span' is only available from C++20 onwards
  272 |   std::span<T> mutable_span_as() {
      |   ^~~
```

Additionally, use C++14 as the minimum standard, falling back from C++20 where unavailable.
C++11 was skipped as it is no longer the default on currently supported OSs.

Since the "AX_CXX_COMPILE_STDCXX_20" macro was not being expanded correctly,
I changed the syntax to "AX_CXX_COMPILE_STDCXX([20], ...)" to ensure proper macro expansion.