cmake: suppress frame-larger-than warning for llama.cpp (#2463)
## Issue

We got the following error when we built Groonga with MariaDB.

```
/home/buildbot/_deps/llama_cpp-src/ggml/src/ggml-cpu/ggml-cpu-aarch64.cpp:4797:1: error: the frame size of 37952 bytes is larger than 16384 bytes [-Werror=frame-larger-than=]
 4797 | }
      | ^
cc1plus: all warnings being treated as errors
```

## Cause

When building Groonga with MariaDB, the bundled llama.cpp triggers
`-Werror`.

## Solution

Upstream llama.cpp doesn't setup frame-larger-than, so we suppress the
warning by explicitly passing -W-Wno-frame-larger-than in Debug and
RelWithDebInfo builds.