cmake llama.cpp: suppress the missing-braces warning (#2567)
## Issue

We got the following error when we built Groonga with MariaDB.

```
/home/buildbot/_deps/llama_cpp-src/src/llama-batch.h:126:48: error: missing braces around initializer for 'std::__array_traits<int, 1>::_Type' {aka 'int [1]'} [-Werror=missing-braces]
```

## Cause

When building Groonga with MariaDB, the bundled llama.cpp triggers
`-Werror`.

## Solution

Upstream llama.cpp doesn't setup `-Wmissing-braces`, so we suppress the
warning by explicitly passing `-Wno-missing-braces` in Debug and
RelWithDebInfo builds.