onigmo: suppress deprecated-non-prototype warning as workaround
It's just a workaround. We should fix this in Onigmo.

    /home/runner/work/groonga/groonga/vendor/onigmo-source/st.c:310:50:
    error: passing arguments to a function without a prototype is
    deprecated in all versions of C and is not supported in C23
    [-Werror,-Wdeprecated-non-prototype]
     310 |     st_hash_t hash = (st_hash_t)(tab->type->hash)(key);
         |                                                  ^