ci release: fix gem load error (#2324)
GitHub: GH-2315

## Problem

In release workflow, the following error happened
because gem `x` isn't loaded.

```
Run VERSION=${GITHUB_REF_NAME#v} rake release:announce
  VERSION=${GITHUB_REF_NAME#v} rake release:announce
  shell: /usr/bin/bash -e {0}
  env:
    X_API_KEY: ***
    X_API_KEY_SECRET: ***
    X_ACCESS_TOKEN: ***
    X_ACCESS_TOKEN_SECRET: ***
git ls-files
rake aborted!
LoadError: cannot load such file -- x (LoadError)
<internal:/opt/hostedtoolcache/Ruby/3.4.3/x64/lib/ruby/3.4.0/rubygems/core_ext/kernel_require.rb>:136:in 'Kernel#require'
<internal:/opt/hostedtoolcache/Ruby/3.4.3/x64/lib/ruby/3.4.0/rubygems/core_ext/kernel_require.rb>:136:in 'Kernel#require'
/home/runner/work/groonga/groonga/Rakefile:223:in 'block (2 levels) in <top (required)>'
Tasks: TOP => release:announce
(See full trace by running task with --trace)
```

## Solution

Using `bundle exec` loads gems including gem `x` in Gemfile.
And also we added the dry-run mode to check whether the announcement
works or not.