ts: add workaround to fix build error with MSVC
MSVC doesn't support empty struct.

https://ci.appveyor.com/project/groonga/groonga/build/2521/job/ni8sqlf6etpooumy#L982

    c:\projects\groonga\lib\ts\ts_sorter.h(31): error C2016: C requires that a struct or union has at least one member [C:\projects\groonga\lib\libgroonga.vcxproj]