Add missing scorer.h in packaged source
Because following error occcurred in nightly package:

```log
 c:\jw\workspace\dmbvc2013\powershell\work\source\storage\mroonga\vendor\groonga\lib\grn_db.h(27):
 fatal error C1083: include ファイルを開けません。'groonga/scorer.h':No
 such file or directory
 (C:\jw\workspace\dmbvc2013\powershell\work\source\storage\mroonga\vendor\groonga\lib\command.c)
 [C:\jw\workspace\dmbvc2013\powershell\work\build-vc2013-zip-32\storage\mroonga\vendor\groonga\lib\libgroonga.vcxproj]
```