db: add missing header for "grn_fopen()"
"grn_fopen()" is defined "_fsopen()" in Windows.

We can specify "shflag" in the third argument of "_fsopen()".
We use "shflg" in "_fsopen()".

We need to include "share.h" to use "shflag".
See: https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/fsopen-wfsopen?view=msvc-160

However, db.c does not include "share.h".
So, "error C2065: '_SH_DENYNO': undeclared identifier" occur.

This problem only occur in Groonga for Windows.
Because "fopen()" does not have "shflag".
("grn_fopen()" is defined "fopen()" in Linux.)