Add missing include
This fixes the followiong warning:

    expr.c: In function 'scan_info_build':
    expr.c:4065:5: warning: implicit declaration of function 'grn_mrb_scan_info_build' [-Wimplicit-function-declaration]
         return grn_mrb_scan_info_build(ctx, expr, n, op, size);
         ^