windows: fix compilation errors on ARM64 (#2653)
## Issue

Compilation fails on ARM64 Windows CI with the following error:

```
lib/windows.c:408:4: error: "Intel x86, Intel Itanium and x64 are only supported architectures"
  408 | #  error "Intel x86, Intel Itanium and x64 are only supported architectures"
      |    ^
1 error generated.
```

## Cause

The stack walking code in `lib/windows.c` only supports Intel x86, Intel
Itanium, and x64 architectures. ARM64 architecture was not recognized.

## Solution

Add support for the `_M_ARM64` compiler macro and
configure the StackWalk64 API with ARM64-specific
registers. msys2 packages use the same approach:

- `Pc` (Program Counter)
- `Fp` (Frame Pointer)
- `Sp` (Stack Pointer)

ref:
https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-groonga/001-aarch64.patch
ref:
https://developer.arm.com/documentation/102374/0103/Registers-in-AArch64---other-registers
ref:
https://learn.microsoft.com/en-us/windows/win32/api/winnt/ns-winnt-arm64_nt_context

Also update the error message to include ARM64 in the list of supported
architectures.