cmake llama.cpp: suppress the `discarded-qualifiers` warning (#2560)
## Issue

We got the following error when we built Groonga with MariaDB.

```
/home/buildbot/_deps/llama_cpp-src/ggml/src/ggml-cpu/ggml-cpu.c:3567:24: error: passing argument 1 of 'putenv' discards 'const' qualifier from pointer target type [-Werro =discarded-qualifiers]
```

## Cause

When building Groonga with MariaDB, the bundled llama.cpp triggers
`-Werror`.

## Solution

Upstream llama.cpp doesn't setup discarded-qualifiers, so we suppress
the warning by explicitly passing `-Wno-discarded-qualifiers` in Debug
and RelWithDebInfo builds.