mingw: force to use 64bit version to work with debug build
localtime_s() and gmtime_s() are defined as inline function without
static in MinGW. The inline functions aren't inlined with -O0 build.
So localtime_s() and gmtime_s() symbols aren't found:

    .libs/ctx.o: In function `grn_timeval2tm':
    lib/ctx.c:141: undefined reference to `localtime_s'
    .libs/str.o: In function `grn_text_time2rfc1123':
    lib/str.c:2447: undefined reference to `gmtime_s'
    collect2: error: ld returned 1 exit status