ci package ubuntu focal: add missing Threads::Threads dependencies (#2105)
CI failed because `groonga-suggest-learner` & `groonga-suggest-httpd`
couldn't be linked to `libpthread.so.0` like the followings.

- `groonga-suggest-learner`

```
...
[400/416] : && /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/groonga-14.1.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -O2 -g -DNDEBUG  -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now src/suggest/CMakeFiles/groonga-suggest-learner.dir/groonga_suggest_learner.c.o  -o src/suggest/groonga-suggest-learner  -Wl,-rpath,/build/groonga-14.1.1/obj-x86_64-linux-gnu/lib:  src/suggest/libgroonga-suggest-util.a  lib/libgroonga.so.0.0.0  /usr/lib/x86_64-linux-gnu/libmsgpackc.so  /usr/lib/x86_64-linux-gnu/libevent.so  /usr/lib/x86_64-linux-gnu/libzmq.so && :
FAILED: src/suggest/groonga-suggest-learner 
: && /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/groonga-14.1.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -O2 -g -DNDEBUG  -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now src/suggest/CMakeFiles/groonga-suggest-learner.dir/groonga_suggest_learner.c.o  -o src/suggest/groonga-suggest-learner  -Wl,-rpath,/build/groonga-14.1.1/obj-x86_64-linux-gnu/lib:  src/suggest/libgroonga-suggest-util.a  lib/libgroonga.so.0.0.0  /usr/lib/x86_64-linux-gnu/libmsgpackc.so  /usr/lib/x86_64-linux-gnu/libevent.so  /usr/lib/x86_64-linux-gnu/libzmq.so && :
/usr/bin/ld: src/suggest/CMakeFiles/groonga-suggest-learner.dir/groonga_suggest_learner.c.o: undefined reference to symbol 'pthread_join@@GLIBC_2.2.5'
/usr/bin/ld: /lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
...
```

- groonga-suggest-httpd

```
...
[403/416] : && /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/groonga-14.1.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -O2 -g -DNDEBUG  -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now src/suggest/CMakeFiles/groonga-suggest-httpd.dir/groonga_suggest_httpd.c.o  -o src/suggest/groonga-suggest-httpd  -Wl,-rpath,/build/groonga-14.1.1/obj-x86_64-linux-gnu/lib:  src/suggest/libgroonga-suggest-util.a  lib/libgroonga.so.0.0.0  /usr/lib/x86_64-linux-gnu/libmsgpackc.so  /usr/lib/x86_64-linux-gnu/libevent.so  /usr/lib/x86_64-linux-gnu/libzmq.so && :
FAILED: src/suggest/groonga-suggest-httpd 
: && /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/groonga-14.1.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -O2 -g -DNDEBUG  -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now src/suggest/CMakeFiles/groonga-suggest-httpd.dir/groonga_suggest_httpd.c.o  -o src/suggest/groonga-suggest-httpd  -Wl,-rpath,/build/groonga-14.1.1/obj-x86_64-linux-gnu/lib:  src/suggest/libgroonga-suggest-util.a  lib/libgroonga.so.0.0.0  /usr/lib/x86_64-linux-gnu/libmsgpackc.so  /usr/lib/x86_64-linux-gnu/libevent.so  /usr/lib/x86_64-linux-gnu/libzmq.so && :
/usr/bin/ld: src/suggest/CMakeFiles/groonga-suggest-httpd.dir/groonga_suggest_httpd.c.o: undefined reference to symbol 'pthread_join@@GLIBC_2.2.5'
/usr/bin/ld: /lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
...
```

So we added Threads::Threads to the dependencies.