grn_column_find_index_data(): returns accessor itself as index
Exception: One level accessor such as _key. Index column is returned
for _key as before.

CAUTION: This may cause performance regression by unexpected index
resolution failure. If we can't resolve index unexpectedly, we execute
query by sequential search. We need to test performance regression
until the next release.

grn_table_select_index() resolves nested index by
grn_accessor_execute(). It means that all operations support nested
index now.

Selectors don't need to care nested index. It's resolved by
grn_table_select_index(). selector_prefix_rk_search() doesn't need to
resolve nested index by this change.

Selectors don't need NULL check for index. If index isn't resolved,
selectors aren't called. grn_selector_geo_in_circle() and
grn_selector_geo_in_rectangle() remove NULL check for index.

Exception: Selectors that uses GRN_OP_NOP as selector operator must
resolve nested index by grn_accessor_execute(). And they must resolve
suitable index by themselves.

selector_fuzzy_search() uses GRN_OP_NOP by this change. Because it
wants to process sequential search in selector.